apiVersion: v1
kind: Service
metadata:
  labels: 
    app: nginx 
  name: nginx-service
  namespace: default   
spec:
  ports:
  - port: 80
    protocol: TCP
    tergatePort: 80
  selector:
    app: nginx
  type: NodePort    
      

